### PR TITLE
feat: merged shadcn feature branch and atom graph tab feature branch

### PR DESCRIPTION
**Pull request by tori-obregon**
- shadcn component ui library added
- atom graph tab added with react flow container (todo: add atoms as nodes)

### CODE REVIEW

**Review by adamkim1006 — APPROVED** [review]
Aweeesome! Everything's working great :D

**Review by WebDevMcFarland — COMMENTED** [review]
Wow, excellent job guys! This was a big merge and it seems to be working on my end. Good work getting through those blocks today, excited to see the changes over the next week. Approved.

**Review by stan-louie — APPROVED** [review]
Beautiful job team, lots of progress today!

**Review by WebDevMcFarland — APPROVED** [review]
Wow, excellent job guys! This was a big merge and it seems to be working on my end. Good work getting through those blocks today, excited to see the changes over the next week. Approved.

**Pull request merged**
