### PR TITLE
feat(devtool): added noatoms story to test when no atoms are present, added storybook-static to eslintignore, all button conditional for AtomGrapList

### PR DESCRIPTION
**Pull request by tori-obregon**

### CODE REVIEW

**Review by stan-louie — APPROVED** [review]
Good test, approved.

**Review by adamkim1006 — APPROVED** [review]
Looks good Victoria! Thank you

**Review by WebDevMcFarland — APPROVED** [review]
Nice, good work on the error message! Approved.

**Comment by WebDevMcFarland** [comment]
Confirming merge with mainApril

**Pull request merged**
